In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../Data/top100_ai_tools_2026.csv")
df

,Rank,Tool_Name,Primary_Category,Sub_Category,Pricing_Model,Starting_Price_USD,Monthly_Traffic_Est,User_Rating,Agentic_Capability_Score,API_Available,Release_Year,Active_Users_Est,Description
0,1,ChatGPT,Conversational AI,General Assistant,Freemium,20.00,1800000000,4.80,9.50,Yes,2022,180000000,"OpenAI's flagship conversational AI for text, ..."
1,2,Gemini,Conversational AI,Multimodal AI,Freemium,19.99,500000000,4.70,9.30,Yes,2023,90000000,Google's multimodal AI integrated with Google ...
2,3,Canva AI,Image Generation,Design Assistant,Freemium,15.00,500000000,4.60,6.00,Yes,2023,170000000,AI design tools integrated in Canva
3,4,Character.AI,Conversational AI,Roleplay & Chat,Freemium,9.99,300000000,4.30,6.00,No,2022,20000000,AI characters for entertainment and roleplay
4,5,Claude,Conversational AI,General Assistant,Freemium,20.00,200000000,4.80,9.40,Yes,2023,50000000,Anthropic's safety-focused AI assistant with l...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,Koral Bot,Research & Search,Market Research,Paid,196.25,114463,4.10,6.08,No,2023,38201,AI research assistant for faster knowledge dis...
496,497,Quill Flow,HR & Recruiting,Employee Onboarding,Paid,71.45,101182,4.18,7.39,Yes,2023,3464,AI recruitment and HR automation platform
497,498,Cipher GPT,Legal AI,Legal Research,Paid,414.84,88779,4.38,7.20,Yes,2023,18600,"AI platform for legal research, drafting, and ..."
498,499,Quill GPT,HR & Recruiting,Employee Onboarding,Paid,84.36,80270,4.22,7.35,Yes,2021,14974,AI recruitment and HR automation platform
499,500,Cipher Flow,Cybersecurity AI,Threat Detection,Paid,0.00,65878,4.45,8.25,Yes,2021,8912,AI-powered cybersecurity and threat intelligen...

# 1. How big data is?

In [3]:
df.shape

(500, 13)

# 2. Data looks like

In [4]:
df.sample(10)

,Rank,Tool_Name,Primary_Category,Sub_Category,Pricing_Model,Starting_Price_USD,Monthly_Traffic_Est,User_Rating,Agentic_Capability_Score,API_Available,Release_Year,Active_Users_Est,Description
172,173,Durable,Web Builder,Website Creation,Paid,15.00,2000000,4.00,5.50,No,2022,200000,AI website builder for small businesses
437,438,Arcane Lab,Automation,RPA + AI,Paid,247.22,348235,4.40,8.05,Yes,2022,71263,AI workflow automation for business process ef...
184,185,Karma Pro,Video Generation,AI Thumbnail,Freemium,12.68,1998276,3.92,4.61,No,2025,78855,AI-powered video creation and editing platform
153,154,Neon Engine,Education,Homework Helper,Paid,17.57,2332169,4.28,6.36,No,2021,325516,AI-powered educational tool for personalized l...
497,498,Cipher GPT,Legal AI,Legal Research,Paid,414.84,88779,4.38,7.20,Yes,2023,18600,"AI platform for legal research, drafting, and ..."
441,442,Iris Suite,Healthcare AI,Medical Imaging,Paid,0.00,341296,4.40,5.70,Yes,2023,5106,AI solution for healthcare data analysis and c...
29,30,Jira AI,Productivity,Issue Tracking,Freemium,8.15,30000000,4.20,6.50,Yes,2023,10000000,AI features in Atlassian Jira
273,274,Cleanvoice,Audio & Voice,Audio Cleanup,Freemium,11.00,1000000,4.20,3.50,Yes,2021,100000,AI filler word and silence remover for podcasts
224,225,Lyric Vision,Developer Tools,Prompt Engineering,Paid,27.69,1469672,4.27,8.59,No,2023,132740,AI developer tool for building smarter applica...
134,135,Linear AI,Productivity,Issue Tracking,Paid,8.00,3000000,4.60,6.00,Yes,2023,100000,AI features in Linear project management

# 3. Data type of the columns

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Rank                      500 non-null    int64
 1   Tool_Name                 500 non-null    str
 2   Primary_Category          500 non-null    str
 3   Sub_Category              500 non-null    str
 4   Pricing_Model             500 non-null    str
 5   Starting_Price_USD        500 non-null    float64
 6   Monthly_Traffic_Est       500 non-null    int64
 7   User_Rating               500 non-null    float64
 8   Agentic_Capability_Score  500 non-null    float64
 9   API_Available             500 non-null    str
 10  Release_Year              500 non-null    int64
 11  Active_Users_Est          500 non-null    int64
 12  Description               500 non-null    str
dtypes: float64(3), int64(4), str(6)
memory usage: 50.9 KB

# 4. Missing Values

In [6]:
df.isnull().mean() * 100

Rank                        0.0
Tool_Name                   0.0
Primary_Category            0.0
Sub_Category                0.0
Pricing_Model               0.0
Starting_Price_USD          0.0
Monthly_Traffic_Est         0.0
User_Rating                 0.0
Agentic_Capability_Score    0.0
API_Available               0.0
Release_Year                0.0
Active_Users_Est            0.0
Description                 0.0
dtype: float64

In [7]:
df.dropna(inplace=True)

# 5. all statistical information

In [8]:
df.describe()

,Rank,Starting_Price_USD,Monthly_Traffic_Est,User_Rating,Agentic_Capability_Score,Release_Year,Active_Users_Est
count,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02
mean,250.500000,61.616940,1.189889e+07,4.285060,6.610580,2022.138000,1.948661e+06
std,144.481833,94.884544,8.868521e+07,0.171419,1.494926,2.463146,1.246835e+07
min,1.000000,0.000000,6.587800e+04,3.800000,2.000000,2009.000000,3.510000e+02
25%,125.750000,12.000000,6.152182e+05,4.157500,5.600000,2021.000000,3.296050e+04
50%,250.500000,24.000000,1.148314e+06,4.290000,6.630000,2023.000000,8.589150e+04
75%,375.250000,71.572500,3.000000e+06,4.400000,7.610000,2024.000000,2.620055e+05
max,500.000000,1000.000000,1.800000e+09,4.800000,9.940000,2025.000000,1.800000e+08

# 6. Duplicate value check and remove

In [9]:
df.duplicated().sum()

np.int64(0)