In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../../Data/Housing_Data.csv",usecols=['LotFrontage','GarageQual','SalePrice'])
df

      LotFrontage GarageQual  SalePrice
0            65.0         TA     208500
1            80.0         TA     181500
2            68.0         TA     223500
3            60.0         TA     140000
4            84.0         TA     250000
...           ...        ...        ...
1455         62.0         TA     175000
1456         85.0         TA     210000
1457         66.0         TA     266500
1458         68.0         TA     142125
1459         75.0         TA     147500

[1460 rows x 3 columns]

In [3]:
df.isnull().mean() * 100

LotFrontage    17.739726
GarageQual      5.547945
SalePrice       0.000000
dtype: float64

In [4]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, :-1], df.iloc[:, -1], test_size=0.2, random_state=42)
X_train

      LotFrontage GarageQual
254          70.0         TA
1066         59.0         TA
638          67.0        NaN
799          60.0         TA
380          50.0         TA
...           ...        ...
1095         78.0         TA
1130         65.0         TA
1294         60.0         TA
860          55.0         TA
1126         53.0         TA

[1168 rows x 2 columns]

In [5]:
X_train['GarageQual'].value_counts()

GarageQual
TA    1050
Fa      36
Gd      13
Ex       3
Po       2
Name: count, dtype: int64

# KNN Imputation (Only numerical Data)

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.preprocessing import OrdinalEncoder

cat_pipe = Pipeline([
    ("cat_imp", SimpleImputer(strategy='most_frequent')),
    ("encod",OrdinalEncoder(categories=[['Po','TA','Fa','Gd','Ex']]))
])

imp_trf = ColumnTransformer(transformers=[
    ("num_imp", KNNImputer(n_neighbors=3, weights='distance'), ['LotFrontage']),
    ("cat_pipe", cat_pipe, ['GarageQual'])
])

In [11]:
X_train_trf = imp_trf.fit_transform(X_train)
X_test_trf = imp_trf.transform(X_test)