In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../Data/cars.csv")
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['selling_price']), df['selling_price'], test_size=0.2, random_state=42)

In [4]:
X_train_encod = X_train[['fuel','owner']]
X_test_encod = X_test[['fuel','owner']]

In [5]:
X_train_encod['fuel'].value_counts()

fuel
Diesel    3545
Petrol    2880
CNG         46
LPG         31
Name: count, dtype: int64

In [6]:
X_train_encod['owner'].value_counts()

owner
First Owner             4240
Second Owner            1684
Third Owner              433
Fourth & Above Owner     141
Test Drive Car             4
Name: count, dtype: int64

In [7]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse_output=False, dtype=np.int32)

X_train_encod = ohe.fit_transform(X_train_encod)
X_test_encod = ohe.transform(X_test_encod)

In [10]:
X_train_encod = np.hstack((X_train[['brand','km_driven']], X_train_encod))
X_test_encod = np.hstack((X_test[['brand','km_driven']], X_test_encod))
X_train_encod

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], shape=(6502, 9), dtype=object)

# One Hot Encoding with top categories

In [14]:
value_count = X_train['brand'].value_counts()
value_count

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [16]:
threshold = 100
replace_index = value_count[value_count <= threshold].index
replace_index

Index(['BMW', 'Skoda', 'Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz',
       'Fiat', 'Audi', 'Jeep', 'Lexus', 'Mitsubishi', 'Force', 'Land', 'Kia',
       'Ambassador', 'MG', 'Daewoo', 'Isuzu', 'Ashok', 'Peugeot', 'Opel'],
      dtype='str', name='brand')

In [17]:
new_brand = pd.get_dummies(X_train['brand'].replace(replace_index,'other_brand'))
new_brand

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Tata,Toyota,Volkswagen,other_brand
6518,False,False,False,False,False,False,False,True,False,False,False
6144,False,False,True,False,False,False,False,False,False,False,False
6381,False,False,False,True,False,False,False,False,False,False,False
438,False,False,False,False,False,True,False,False,False,False,False
5939,False,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
5226,False,False,False,False,True,False,False,False,False,False,False
5390,False,False,False,False,False,True,False,False,False,False,False
860,False,False,False,True,False,False,False,False,False,False,False
7603,False,False,False,False,False,True,False,False,False,False,False
7270,False,False,False,False,False,True,False,False,False,False,False